### PR TITLE
Switch from phpcs to php-cs-fixer

### PR DESCRIPTION
**Pull request by Hywan**
Pros of php-cs-fixer

* PSR-1 and PSR-2 “level” (a set of fixers), even if we use only PSR-1, it's easier to define it.
* a lot of [pre-defined fixers](https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage).
* we can write our own fixers easily (since we have specific CS, it's useful).
* can **check** and **fix** CS for us (`--dry-run` to check, nothing to fix).
* configuration file is pure PHP, which I assume to be easier to read than XML in this case.

This is why I suggest to switch to php-cs-fixer. We can easily apply this tool to existing sabre/* libraries.

So far, I used pre-defined filters. I am going to add new filters for the specific rules of sabre/* projects.

Here is the list (potentially updated frequently) of fixers:
* PSR-1 level (no PSR-2, like discussed),
* `align_double_arrow`,
* `align_equals`,
* `blankline_after_open_tag`,
* `concat_with_spaces`,
* `elseif`,
* `eol_ending`,
* `function_call_space`,
* `function_declaration`,
* `indentation`,
* `line_after_namespace`,
* `linefeed`,
* `lowercase_constants`,
* `lowercase_keywords`,
* `method_argument_space`,
* `parenthesis`,
* `php_closing_tag`,
* `self_accessor`,
* `short_array_syntax`,
* `single_line_after_imports`,
* `spaces_cast`,
* `trailing_spaces`,
* `unused_use`,
* `visibility`.

### CODE REVIEW

**Comment by Hywan** [comment]
We can use php-cs-fixer to fix the copyright with a custom fixer (see for instance https://github.com/hoaproject/Devtools/blob/master/Resource/PHPCSFixer/Fixer/Copyright.php).

**Comment by Hywan** [comment]
PR #166 is an example of the result when we run this PR.

**Comment by Hywan** [comment]
This PR fails because php-cs-fixer finds some issues with this PR. Let's focus on the tests to check any regressions first.

**Comment by Hywan** [comment]
I would like to fix `{` and newlines. What is the rule? (It is not specified in https://github.com/fruux/sabre-dav/blob/master/CONTRIBUTING.md#coding-standards).

Case A:
```
{
    statement;
}
```

Case B:
```
{

    statement;

}
```

Case C:
```
{
    statement;
    statement;
}
```

Case D:
```
{

    statement;
    statement;

}
```

For what I understood in sabre/dav, this is a A and D: One statement = no empty lines, more than one statement = two surrounding empty lines.

Because such a fixer will be difficult to implement and because this rule is not applied everytime, I would like to discuss about what rule to adopt. I suggest A, except for classes and functions where one empty line will be present after `{`, something like:
```php
class C {

    function f() {

        statement;

        if (predicate) {
            statement;
            statement;
        }
    }
}
```

Thought @fruux/developers?

**Comment by evert** [comment]
The way I've been going about it is that I've basically never really spent time thinking about this.

I'm kind of on team : "do we really need a rule for this?"

Your example though looks nice, but I think that's option E not option A as the function opening is also followed by a newline.

**Comment by DominikTo** [comment]
So, should we give it a test run with katana, @evert? :-)

**Comment by evert** [comment]
Yes I would _definitely_ be happy to switch to php-cs-fixer. It looks a *lot* nicer. Does it also fail travis builds if it's wrong?

**Comment by evert** [comment]
I would actually be cool with switching every project

**Comment by DominikTo** [comment]
Yup, seems to [trigger](https://travis-ci.org/fruux/sabre-katana/jobs/60194285) failed Travis builds.

**Comment by DominikTo** [comment]
Should we also use the following?

* operators_spaces
* function_call_space

If we're going to use this everywhere, does it make sense to have a sabre/cs package we can include, @evert?

**Comment by evert** [comment]
not a bad idea to make a sabre/cs (dev-only) package.

**Comment by evert** [comment]
both of those rules seem fine too but also kind of fall into a category of 'does it really matter'. it doesn't really change legibility too much to me. But if everyone else thinks that it's important to have hard rules for those, I'm cool with adding them =)

**Comment by Hywan** [comment]
Yes, php-cs-fixer makes the Travis build fail if needed. It produces a diff in this case.

You probably noticed I “imported” all rules from PSR-2, except the braces fixer. That's the only one ;-). I am thinking of still applying it and partly reversing it, because it's kind of tricky to deal with all braces. Especially because we mainly focus on one type of them.

So, we decide for E, so exactly this:
```php
class C {

    function f() {

        statement;

        if (predicate) {
            statement;
            statement;
        }
    }
}
```

Correct?

**Comment by evert** [comment]
yes if you guys think it's important to have a hard rule, I think that I would go indeed for option E

**Comment by Hywan** [comment]
From my point of view, braces is the most important rule :stuck_out_tongue:. It defines blocks and so it defines how we see the flow of data. Everything else is less important for me. I would like to have the opinion of @armin-hackmann on this one (he codes a lot in sabre/ and fruux/ codes, its opinion is important too).

**Comment by evert** [comment]
Ah I mean not the 'location of braces' I think they should go on the same line as the declaration, but I meant the amount of spacing before and after braces.

**Comment by Hywan** [comment]
Close in favor or sabre/cs.

**Pull request closed without merging**
