### PR TITLE
Composer: Update dependencies and drop PHP5.4 to 5.5

### PR DESCRIPTION
**Pull request by Hywan**
Also, we drop PHP5.4 for 5.5!

### CODE REVIEW

**Comment by Hywan** [comment]
Only CS are failing. It works with the lowest sabre-cs-fixer version and it fails with the highest one. What am I supposed to do :-]? /cc @evert

**Comment by evert** [comment]
Just depend on the latest one =) and thnx!

**Comment by Hywan** [comment]
@evert Running.

**Comment by Hywan** [comment]
@evert I gave up. Adding them: Errors. Removing them: Errors. I don't get it. `sabre-cs-fixer` does not find anything on my local machine, so it does not help. Any idea?

**Comment by evert** [comment]
Try depending on sabre/cs 0.0.5 and re-run.

**Comment by DominikTo** [comment]
The sabre/cs v0.5 fixer applied changes for me (basically only removing the newline between the initial comment block and the namespace).

@Hywan: If you run `bin/sabre-cs-fixer fix --diff .` in the projects root, it should work for you, too.

**Comment by DeepDiver1975** [comment]
trying to re-vive this in #318

**Pull request closed without merging**
