### PR TITLE
Apache support

### PR DESCRIPTION
**Pull request by Hywan**
Address #9.

### CODE REVIEW

**Comment by DominikTo** [comment]
Should we replace `dav` with `katana` as the default directory?

**Comment by evert** [comment]
:+1:

**Comment by evert** [comment]
Also see here for a better config:

https://github.com/fruux/sabre-dav/blob/master/examples/webserver/apache2_vhost.conf

**Comment by evert** [comment]
This configuration also assumes fastcgi. I think most apache people would use mod_php.

**Comment by Hywan** [comment]
> Hywan wants to merge 3 commits into fruux:master from unknown repository

“unknown repository”, huh? Opening a new PR.

**Pull request closed without merging**
