### PR TITLE
Forcing all hoa depenencies to be the latest.

### PR DESCRIPTION
**Pull request by evert**
Hopefully this fixes the build

### CODE REVIEW

**Comment by evert** [comment]
Hey @Hywan, all my builds are failing. I made sure that I'm using the latest Hoa and Atoum packages, but I'm not really sure why this is happening. Any clue?

**Comment by Hywan** [comment]
@evert Apparently our attempt to not introduce a BC break in atoum has failed. The linked PR updates atoum and our thin layer on top of it. Let's wait and see if tests are green.

**Comment by Hywan** [comment]
(so no need to update all Hoa's dependencies, except if you would like to)

**Comment by evert** [comment]
Thank you!

**Pull request closed without merging**
