### PR TITLE
Renamed digesta1 to passwordhash and changed columns to VARBINARY.

### PR DESCRIPTION
**Pull request by evert**
Work in progress, haven't tested yet.

### CODE REVIEW

**Comment by Hywan** [comment]
You are probably likely to rebase onto master in a minute.

**Comment by evert** [comment]
Currently getting this error:

```
An error occured: fstat() expects parameter 1 to be resource, boolean given
```

But not sure why yet

**Comment by Hywan** [comment]
You can rebase now.

**Comment by Hywan** [comment]
@evert: Probably because a file does not exist. Did you `make uninstall`?

**Pull request closed without merging**
