### PR TITLE
Serve files with appropriated MIME type

### LINKED ISSUE #241: Serve files with appropriated MIME type
It will allow browser to show files instead of forcing them to download.

### PR DESCRIPTION
**Pull request by Hywan**
Fix #241.

Progression:
* [x] Serve MIME type,
* [x] Restrict MIME type database.

### CODE REVIEW

**Comment by evert** [comment]
So.. for security reasons I think it's important that the mimetype list is whitelist (not blacklist) based. We need to know for each format if it's secure. We might be able to get away with a relatively small subset, because only really the formats a browser supports are the most relevant.

I also wonder out loud how Hoa\Mime works. Does it just use the filename or does it inspect the file itself? If it looks inside the file, how slow does it get when there are hundreds of files in a directory?

**Comment by Hywan** [comment]
Yup, it will be white-listed :-).

**Comment by Hywan** [comment]
And `Hoa\Mime` either works by looking at the stream, or directly with an extension. Here, for performance reason, we use extension-based detection. So pretty fast ;-).

**Comment by evert** [comment]
Brilliant :+1:

**Comment by Hywan** [comment]
I would whitelist basically almost all `audio`, `image` and `text` media. The keyword here is “almost”. Just reviewing my patch.

**Comment by Hywan** [comment]
We basically allow almost all:

  * `audio`,
  * `font`,
  * `image`,
  * `text`,
  * and `video` medias.

We add archives, PDF, some vendor video format, office documents etc. We take care to disable HTML by default.

**Comment by Hywan** [comment]
What if we enable HTML but disable Javascript? Would it work?

**Comment by evert** [comment]
I don't think we can reliably do that yet... CSP mostly works, but it's intended as a 'last line of defence', not the prime means of security.

This also extends to css, svg, text/javascript, and many others. I'd even be a little worried about pdf and office file formats (can vbscript do bad things?).

**Comment by Hywan** [comment]
@evert Good question :-/. I don't know. We can still disable CSS and SVG, yup.

**Comment by Hywan** [comment]
Done here: https://github.com/fruux/sabre-katana/commit/af7e51f6b29134d61c0713e4d87d9e95891ee5d7.

**Pull request merged**
