### PR TITLE
Cleaning up filesystem-related code.

### PR DESCRIPTION
**Pull request by evert**
This patch intends to remove:

* Everything related to the `katana://` stream wrapper.
* Everything that uses `Hoa\File` that can be easily replaced by PHP's plain filesystem wrappers.
* For now it also removes the exception handlers. I don't think they work particularly well and they add a few non-idiomatic constructs. In the development phase I believe we are better off just not catching exceptions, and address in the future again where this might cause us issues.
* Removed the `Database` class, in favor of using PHP's PDO class.
* Moved the version constants to their own class, to make it consistent with other sabre projects.

This is a work in progress.

See #277

### CODE REVIEW

**Comment by Hywan** [comment]
Can we discuss about these technical choices a little bit?

**Comment by evert** [comment]
Sure! I know this must be a bit frustrating to you, but we need to simplify. Abstracting the filesystem might have given some marginal gain, but it's been at the cost of an unfamiliar and hard to debug API.

**Comment by Hywan** [comment]
From my point of view, we have just one bug with a not very helpful error message. Could we just fix that and wait for another hard to understand bug to happen before taking these decisions? `katana://` is very helpful…

**Comment by Hywan** [comment]
And I am afraid we introduce a new regression with these changes. The bug #277 is already a regression.

**Comment by evert** [comment]
There's other benefits to having less code and less ivanisms ;) its not the first bug, and it won't be the last.

But the bigger issue is that I see 0 benefit to using in the first place, and it adds several layers if indirection to tasks that are normally pretty straightforward. I've yet to hear the first argument why it was ever benefitial

**Comment by Hywan** [comment]
Let me review your PR then. Regression will be pretty easy to introduce.

**Comment by evert** [comment]
Thank you! I was not fully done though. Got sleepy before I did real testing, so you could also wait till I did that

**Comment by Hywan** [comment]
Sure. Ping me when it's ready for a review :-).

**Comment by Hywan** [comment]
Oh, and why removing `Sabre\Katana\Database`? There is no bug inside it and it's pretty useful :-/.

**Comment by evert** [comment]
There were no methods inside that class anymore.

**Comment by Hywan** [comment]
Except the iterator :-), which is very useful.

**Comment by evert** [comment]
From a pure functionality standpoint the exact same thing is happening now. The difference is that we use a PHP built-in. I can see that it could be useful to move that `glob()` statement to its own function, but it doesn't really need to be a method on a 'Database` class. It's really a separate concern.

**Comment by Hywan** [comment]
Testing `glob` is hard. `glob` is slow. Please, use [`FilesystemIterator`](http://php.net/filesystemiterator.class] :-).

**Comment by evert** [comment]
We're iterating over 5 files that nearly never change. There's no reason to make this more complicated than this is. If we need complexity later, we can add it then.

**Comment by Hywan** [comment]
Fair enough.

**Pull request merged**
