### PR TITLE
WebDAV support

### LINKED ISSUE #76: WebDAV basic support

### PR DESCRIPTION
**Pull request by Hywan**
Fix #76.

Homes will be under the `files/` node. Thus, we will have:
  * `principals/`,
  * `addressbooks/`,
  * `calendars/`,
  * `files/`.

Files will be located in the `katana://data/home/` directory. One directory per principal, as usual. So `katana://data/home/gordon/` for the home of the principal named “gordon”.

Could be awesome to have a new pre-release of sabre/dav because we target the `master` @evert.

### CODE REVIEW

**Comment by Hywan** [comment]
Simple listing (only the root so far):
screen shot 2015-05-13 at 17 34 18

With instructions opened:
screen shot 2015-05-13 at 17 34 28

Thoughts @fruux/developers?

**Comment by Hywan** [comment]
When the principal's home is empty:
screen shot 2015-05-13 at 17 38 29

**Comment by Hywan** [comment]
Demo of the “WebDAV finder”: https://dl.dropboxusercontent.com/u/26317193/Katana_files.webm.

**Comment by DominikTo** [comment]
:+1:

**Comment by Hywan** [comment]
With the breadcrumb:
screen shot 2015-05-15 at 13 58 30

/cc @demkani

**Comment by DominikTo** [comment]
Looks nice!

**Comment by evert** [comment]
beautiful =)

**Pull request merged**
